version: '2'
services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./wordpress:/var/www/html
      - ./ssl/private:/etc/ssl/certs/
    ports:
      - '80:80'
      - '443:443'
    links:
      - wordpress
# php:
#   image: php:7-fpm
#   restart: always
#   volumes:
#      - ./php-fpm/php-fpm.conf:/etc/php-fpm.conf
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    expose:
      - '3306'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=sai@123
      - MYSQL_USER=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_PASSWORD=wordpress
  wordpress:
    image: wordpress:php7.2-fpm
    volumes:
      - ./wordpress:/var/www/html
      - ./php-fpm/:/etc/php-fpm
    restart: always
#   ports:
#     - '9000:9000'
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_PASSWORD=wordpress
    depends_on:
      - db
    
volumes:
   db-data:
   nginx:
   logs:
   wordpress:
